# -*- coding: utf-8 -*-
"""PPT_game.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Kb_9X7jM_2R8r3sPfVJRjkmKAWcWIypR
"""

# -*- coding: cp1252 -*-
import random

def empate():
    print("\nEMPATE!")


def ganaste():
   print("\nGANASTE! :D")
    

def perdiste():
    print("\nPERDISTE! :C")
    

def main():
    print("""Bienvenid@ al juego!
    1 ~ Piedra(🗿)
    2 ~ Papel(📜)
    3 ~ Tijera(✂️)""")
    
    jugadas = ['piedra', 'tijera', 'papel']
    jugador = str(input("\n¿Que deseas jugar? "))
    contrario = jugadas[random.randint(0, 2)]
    
    if jugador == "1":
      jugador = "piedra"
    if jugador == "2":
      jugador = "papel"
    if jugador == "3":
      jugador = "tijera"
    
    jugador = jugador.lower()
    print("\nTu contrario jugó (" + contrario.capitalize() + ") y tu jugaste (" + jugador.capitalize() + ").")

    if jugador == contrario:
      empate()
    elif jugador == "tijera":
      if contrario == "papel":
        ganaste()
      else:
        perdiste()
    elif jugador == "piedra":
      if contrario == "tijera":
        ganaste()
      else:
        perdiste()
    elif jugador == "papel":
      if contrario == "piedra":
        ganaste()
      else:
        perdiste()
    else:
      print("\nERROR: Jugada desconocida...")
    
    
if __name__ == '__main__':
    main()
